### ISSUE TITLE
zerro when reading csv with csvread

### ISSUE THREAD

**Issue by kamaing** [gnu-octave/octave#1]
Hi,

I like to report an issue which came up, when reading a csv file with the csvread function.
Here I have a simple example:

This is a Matrix saved as csv.
![image](https://user-images.githubusercontent.com/37227939/103447513-8b3b8c00-4c8c-11eb-8d4f-fde47e92eb44.png)

When reading this file with csvread, the following result comes up 
![image](https://user-images.githubusercontent.com/37227939/103447532-ce95fa80-4c8c-11eb-8ea9-136fa4b955aa.png)

Note, the first value is zerro.
I am using octave 6.1.0 which I have downloaded as zip file.
![image](https://user-images.githubusercontent.com/37227939/103447557-216fb200-4c8d-11eb-9ee0-f84d4ead8158.png)

**Comment by Andy1978** [comment]
Hi, please attach the CSV rather than images of it in some program you didn't mention. I can just guess that your CSV was saved with a BOM (Byte Order Mark)

**Comment by kamaing** [comment]
I incorporated the csv-file as zip, as github restricts csv somehow.
The csv-file has been created with Microsoft Excel.

[Matrix.zip](https://github.com/gnu-octave/octave/files/5760745/Matrix.zip)

**Comment by siko1056** [comment]
As @Andy1978 suggested, please store the CSV without [BOM](https://en.wikipedia.org/wiki/Byte_order_mark).

![image](https://user-images.githubusercontent.com/8133832/103545199-95f05e00-4ee4-11eb-90ca-82725cb9b31a.png)

**Comment by siko1056** [comment]
Small addition: starting with Octave 7 the BOM will be ignored, see [bug #58813](https://savannah.gnu.org/bugs/?58813).
